blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/meokullu/CalculateETA/discussions
    about: Please ask and answer questions here.
  - name: Issues
    url: https://github.com/meokullu/CalculateETA/issues
    about: Please report security vulnerabilities here.
  - name: Pull Request
    url: https://github.com/meokullu/CalculateETA/pulls
    about: Please do PR here.
